# Generated by Django 6.1 on 2026-08-12 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoirMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_en', models.CharField(max_length=255, verbose_name='Full Name (English)')),
                ('full_name_am', models.CharField(blank=True, max_length=255, verbose_name='Full Name (Amharic)')),
                ('voice_part', models.CharField(choices=[('soprano', 'Soprano'), ('alto', 'Alto'), ('tenor', 'Tenor'), ('bass', 'Bass')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choir_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['voice_part', 'full_name_en'],
            },
        ),
        migrations.CreateModel(
            name='RehearsalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Weekly Rehearsal', max_length=255)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(default='Church Choir Room', max_length=255)),
                ('notes_en', models.TextField(blank=True, verbose_name='Notes / Agenda (English)')),
                ('notes_am', models.TextField(blank=True, verbose_name='Notes / Agenda (Amharic)')),
                ('sheet_music', models.FileField(blank=True, null=True, upload_to='rehearsals/sheets/')),
                ('attendees', models.ManyToManyField(blank=True, related_name='rehearsals_attended', to='rehearsal.choirmember')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
