# Generated by Django 6.1 on 2026-08-11 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_am', models.CharField(blank=True, max_length=255, verbose_name='Title (Amharic)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='albums/covers/')),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_am', models.TextField(blank=True, verbose_name='Description (Amharic)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-release_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.PositiveIntegerField(default=1)),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_am', models.CharField(blank=True, max_length=255, verbose_name='Title (Amharic)')),
                ('audio_file', models.FileField(blank=True, help_text='Upload MP3 or WAV', null=True, upload_to='songs/audio/')),
                ('youtube_url', models.URLField(blank=True, help_text='Link to YouTube video (optional)')),
                ('lyrics_en', models.TextField(blank=True, verbose_name='Lyrics (English)')),
                ('lyrics_am', models.TextField(blank=True, verbose_name='Lyrics (Amharic)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.album')),
            ],
            options={
                'ordering': ['track_number', 'id'],
            },
        ),
    ]
