# Generated by Django 6.1.1 on 2026-10-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Optional mobile phone number for authentication and notifications.', max_length=30, verbose_name='Phone Number'),
        ),
    ]
