# Generated by Django 6.1 on 2026-08-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choir_name_en', models.CharField(default='Horbabicho Kalehiwot Church Yahiwenis Choir', max_length=255)),
                ('choir_name_am', models.CharField(default='ሆርባቢቾ ቃለ ሕይወት ቤተክርስቲያን ያህዌ ንሲ ኳየር', max_length=255)),
                ('hero_banner', models.ImageField(blank=True, help_text='Header image displayed at the top of the home page.', null=True, upload_to='branding/')),
                ('about_text_en', models.TextField(blank=True)),
                ('about_text_am', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
