# Generated by Django 6.1.1 on 2026-09-08 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discussions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('hide_discussion', 'Hide Discussion'), ('restore_discussion', 'Restore Discussion'), ('lock_discussion', 'Lock Discussion'), ('unlock_discussion', 'Unlock Discussion'), ('hide_reply', 'Hide Reply'), ('restore_reply', 'Restore Reply'), ('warn_user', 'Issue Warning to User'), ('suspend_user', 'Suspend User Account'), ('ban_user', 'Ban User Account'), ('unban_user', 'Restore / Unban User Account'), ('resolve_report', 'Resolve Report'), ('dismiss_report', 'Dismiss Report'), ('archive_topic', 'Archive Topic Room')], db_index=True, max_length=30)),
                ('target_repr', models.CharField(max_length=255)),
                ('reason', models.TextField(help_text='Detailed justification for the moderation action.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_taken', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation Audit Log',
                'verbose_name_plural': 'Moderation Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('harassment', 'Harassment or Bullying'), ('hate', 'Hate or Abusive Content'), ('sexual', 'Sexual or Inappropriate Content'), ('threats', 'Threats or Violence'), ('spam', 'Spam or Advertising'), ('misinformation', 'Misinformation or False Teaching'), ('self_harm', 'Self-Harm or Safety Concern'), ('other', 'Other Community Concern')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True, default='', help_text='Provide context to assist moderators in evaluating the report.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('resolved', 'Resolved (Action Taken)'), ('dismissed', 'Dismissed (No Violation)')], db_index=True, default='pending', max_length=20)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
                ('target_discussion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='discussions.discussion')),
                ('target_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='discussions.reply')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Report',
                'verbose_name_plural': 'Content Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='moderation__status_282342_idx')],
            },
        ),
    ]
