# Generated by Django 6.1.1 on 2026-09-08 13:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(help_text='Clear guidance on what issues this room discusses.')),
                ('icon', models.CharField(default='chat-bubble', help_text='Icon identifier for topic card presentation.', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in topic listings.')),
                ('is_archived', models.BooleanField(default=False, help_text='Archived topics are read-only and hidden from active creation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discussion Topic',
                'verbose_name_plural': 'Discussion Topics',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Question details or discussion background.')),
                ('is_anonymous', models.BooleanField(db_index=True, default=False, help_text='When True, identity is strictly obscured from ordinary members.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('locked', 'Locked (No further replies allowed)'), ('hidden', 'Hidden by Moderation')], db_index=True, default='active', max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Internal authenticated author. Preserved for audit/safety.', on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_discussions', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='discussions.topic')),
            ],
            options={
                'verbose_name': 'Discussion Thread',
                'verbose_name_plural': 'Discussion Threads',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='discussions.discussion')),
            ],
            options={
                'verbose_name': 'Discussion Bookmark',
                'verbose_name_plural': 'Discussion Bookmarks',
                'constraints': [models.UniqueConstraint(fields=('user', 'discussion'), name='unique_user_discussion_bookmark')],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_anonymous', models.BooleanField(db_index=True, default=False, help_text='When True, identity is strictly obscured from ordinary members.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden by Moderation')], db_index=True, default='active', max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Internal authenticated author.', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_replies', to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discussions.discussion')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent reply for nested threaded responses.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='discussions.reply')),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['discussion', 'parent', 'created_at'], name='discussions_discuss_6523d9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['topic', '-last_activity_at'], name='discussions_topic_i_804f36_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['author', '-created_at'], name='discussions_author__9ad274_idx'),
        ),
    ]
