# Generated by Django 6.1.1 on 2026-09-16 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='discussions.discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discussion Reaction',
                'verbose_name_plural': 'Discussion Reactions',
                'indexes': [models.Index(fields=['discussion', 'vote_type'], name='discussions_discuss_660281_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'discussion'), name='unique_user_discussion_reaction')],
            },
        ),
    ]
