# Generated by Django 6.1.1 on 2026-09-16 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_reaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='discussions.reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reply Reaction',
                'verbose_name_plural': 'Reply Reactions',
                'indexes': [models.Index(fields=['reply', 'vote_type'], name='discussions_reply_i_8e8169_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'reply'), name='unique_user_reply_reaction')],
            },
        ),
    ]
