# Generated by Django 6.1 on 2026-08-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_am', models.CharField(blank=True, max_length=255, verbose_name='Title (Amharic)')),
                ('event_type', models.CharField(choices=[('service', 'Sunday Service'), ('rehearsal', 'Choir Rehearsal'), ('concert', 'Concert / Special Event'), ('outreach', 'Outreach / Ministry')], default='service', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(default='Horbabicho Kalehiwot Church', max_length=255)),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_am', models.TextField(blank=True, verbose_name='Description (Amharic)')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
